include("cflp/data_reader.jl")
include("cflp/model.jl")
include("cflp/oracle.jl")
include("uflp/data_reader.jl")
include("uflp/model.jl")
include("uflp/oracle.jl")
include("scflp/data_reader.jl")
include("scflp/model.jl")
include("snip/data_reader.jl")
include("snip/model.jl")

include("uflp/model_new.jl")
include("cflp/model_new.jl")
include("scflp/model_new.jl")